### PR TITLE
Handle data URLs better

### PR DESCRIPTION
**Pull request by goromlagche**
Trying to address  https://github.com/rails/rails-html-sanitizer/issues/135

### CODE REVIEW

**Comment by flavorjones** [comment]
Thank you for proposing these changes. I'll take a deeper look shortly.

**Comment by flavorjones** [comment]
I think there's a deeper conversation about the functional drift between Loofah and rails-html-sanitizer, and I've started a discussion about it at https://github.com/rails/rails-html-sanitizer/pull/136

Until that discussion has been had, I'd like to hold off on making a decision about this specific solution.

**Comment by goromlagche** [comment]
That's awesome. I was thinking about something along the line, but just was not sure how to implement the same. :+1:

**Comment by flavorjones** [comment]
Hi, @goromlagche, thanks so much for your patience on this. I'm preparing a security release of Rails::Html::Sanitizer and I've decided to implement a slightly different solution that involves depending on a refactored Loofah class. I'll follow up with you in #135

**Pull request closed without merging**
