### PR TITLE
bumps version of loofah

### PR DESCRIPTION
**Pull request by jeremywrowe**
This is in effort to address https://github.com/flavorjones/loofah/issues/144.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but we don't need to release a new version of rails-html-sanitizer becauase of that. Your application Gemfile can take care of it.

**Comment by jeremywrowe** [comment]
@rafaelfranca Doesn't this need a bump because of the version locking that is happening currently: `spec.add_dependency "loofah", "~> 2.0"`?

**Comment by rafaelfranca** [comment]
No. That allows any version between 2.0.0 and 3.0.0

**Comment by jeremywrowe** [comment]
Hmm okay, I did `bundle update loofah` and the gem stayed the same version. I had thought the same but the update didn't work. Thanks for the clarification. I'll look into it further.

**Comment by jeremywrowe** [comment]
Found it (for others that have the issue), it was another peer dependency that was holding it back. Thanks again rafaelfranca.

**Comment by Em-AK** [comment]
Hi @rafaelfranca,
Reading this I am wondering how the dependency upgrades for this kind of vulnerability is handeled in the rails project ?
Is it done here only at the time of a new release of rails ? or handeled somwhere else at a upper level ?

**Comment by rafaelfranca** [comment]
It is not handled, not only in rails but in any Ruby library. The dependencies of a library is usually to say what is the minimum version of a dependency that works with the library. Security issues in the dependencies don't requires changes in the library, only in the application. This is why your application has a Gemfile that is different from the Gemfile of the library.

**Comment by Em-AK** [comment]
OK, thanks :+1:

**Comment by LouieGeetoo** [comment]
For others who were initially confused about how to get the loofah update (and now the rails-html-sanitizer update), here's what I did:

Say you have just `"rails"` defined in your `Gemfile` -- that is to say, you haven't specifically listed out `"rails-html-sanitizer"` or `"loofah"`.

In that case, all you need to do is update your `Gemfile.lock` to get the fixed versions, which you can do like so:

```
bundle update rails-html-sanitizer loofah
```

Then look in your Gemfile.lock, and you should have `rails-html-sanitizer` with a version of at least `1.0.4` and `loofah` of at least `2.2.2`.

**Pull request closed without merging**
