### PR TITLE
Fix homepage uri in gemspec.

### PR DESCRIPTION
**Pull request by JuanitoFatas**
:wink:

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
Also could you please also add some metadata information of this gem in this page https://rubygems.org/gems/rails-html-sanitizer/edit :pray::

Here are some I know:

| URL                   | VALUE                                      |
| --------------------- | ------------------------------------------ |
| **Source Code URL**   | https://github.com/rails/rails-html-sanitizer               |
| **Documentation URL** | http://www.rubydoc.info/gems/rails-html-sanitizer          |
| **Bug Tracker URL**   | https://github.com/rails/rails-html-sanitizer/issues        |
| **Wiki URL**   | https://github.com/rails/rails-html-sanitizer/wiki        |

Thank you!

**Comment by kaspth** [comment]
Thanks. I don't have access to the gem on rubygems so someone else has to do that.

**Comment by JuanitoFatas** [comment]
> Thanks. I don't have access to the gem on rubygems so someone else has to do that.

OK!

**Comment by JuanitoFatas** [comment]
@kaspth Should keep this issue open till the metadata are done?

**Comment by kaspth** [comment]
It's pull request, so we can't reopen. Let's just wait until people on the other side of the world wake up :smile:

**Comment by JuanitoFatas** [comment]
@kaspth Ah right, it is a pull request....... hahaha! :sweat_smile:

**Pull request merged**
